# Generated by Django 5.0.6 on 2024-07-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default=0.0004940711462450593, max_length=100),
            preserve_default=False,
        ),
    ]
