# Generated by Django 5.0.6 on 2024-07-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0006_course_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('additional_content', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='requirements',
        ),
    ]
