# Generated by Django 5.0.6 on 2024-07-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0011_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
