# Generated by Django 5.0.6 on 2024-07-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0012_successstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='background_image',
            field=models.ImageField(default=0.000819000819000819, upload_to='backgrounds/'),
            preserve_default=False,
        ),
    ]
