# Generated by Django 5.0.6 on 2024-07-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0013_successstory_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successstory',
            name='background_image',
        ),
    ]
